# 선형 회귀 구현

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1) # 랜덤시드 고정

In [2]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

x_train.shape, y_train.shape

(torch.Size([3, 1]), torch.Size([3, 1]))

In [3]:
W = torch.zeros(1, requires_grad=True) # 가중치 W를 0으로 초기화
b = torch.zeros(1, requires_grad=True) # required_grad는 학습을 통해 값을 변경
W, b

(tensor([0.], requires_grad=True), tensor([0.], requires_grad=True))

In [4]:
epochs = 10

for epoch in range(epochs + 1):
    
    H = x_train * W + b # 가설 수립
    C = torch.mean((H - y_train) ** 2) # 손실함수
    
    opt = optim.SGD([W, b], lr=0.01) # 최적화함수
    opt.zero_grad() # 경사를 0으로 초기화
    C.backward() # 손실함수를 미분하여 경사 계산
    opt.step() # W, b 업데이트
    
    print(f'{epoch} / {epochs}  W : {W}, b : {b}, C : {C}') 

0 / 10  W : tensor([0.1867], requires_grad=True), b : tensor([0.0800], requires_grad=True), C : 18.66666603088379
1 / 10  W : tensor([0.3527], requires_grad=True), b : tensor([0.1509], requires_grad=True), C : 14.770962715148926
2 / 10  W : tensor([0.5004], requires_grad=True), b : tensor([0.2138], requires_grad=True), C : 11.691540718078613
3 / 10  W : tensor([0.6318], requires_grad=True), b : tensor([0.2695], requires_grad=True), C : 9.257344245910645
4 / 10  W : tensor([0.7487], requires_grad=True), b : tensor([0.3188], requires_grad=True), C : 7.333169460296631
5 / 10  W : tensor([0.8528], requires_grad=True), b : tensor([0.3625], requires_grad=True), C : 5.812135219573975
6 / 10  W : tensor([0.9453], requires_grad=True), b : tensor([0.4012], requires_grad=True), C : 4.6097636222839355
7 / 10  W : tensor([1.0277], requires_grad=True), b : tensor([0.4353], requires_grad=True), C : 3.65927791595459
8 / 10  W : tensor([1.1011], requires_grad=True), b : tensor([0.4655], requires_grad=T

In [5]:
w = torch.tensor(2.0, requires_grad=True) # 가중치를 초기화하지 않았을 경우
epochs = 10
for epoch in range(epochs + 1):
    z = 2 * w
    z.backward()
    print(f'w : {w.grad}') # 기울기 값을 누적

w : 2.0
w : 4.0
w : 6.0
w : 8.0
w : 10.0
w : 12.0
w : 14.0
w : 16.0
w : 18.0
w : 20.0
w : 22.0


# 자동 미분(Autograd)

In [6]:
w = torch.tensor(2.0, requires_grad=True)
y = w ** 2
z = 2 * y + 5

z.backward() # 수식의 w에 대한 기울기 계산(미분)
w.grad # w 미분값 저장

tensor(8.)

# 다중 선형 회귀

In [7]:
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [8]:
optimizer = optim.SGD([w1, w2, w3, b], lr=1e-5)

epochs = 10
for epoch in range(epochs + 1):
    
    H = x1_train * w1 + x2_train * w2 + x3_train * w3 + b
    C = torch.mean((H - y_train) ** 2)
    
    optimizer.zero_grad()
    C.backward()
    optimizer.step()
    
    print(f'{epoch}/{epochs} {w1.item()}, {w2.item()}, {w3.item()}, {b.item()}, {C.item()}')

0/10 0.29401201009750366, 0.2935999929904938, 0.2973800003528595, 0.0034199999645352364, 29661.80078125
1/10 0.45864337682724, 0.45794832706451416, 0.46387481689453125, 0.005335401743650436, 9298.5205078125
2/10 0.5508393049240112, 0.5499333739280701, 0.5570917725563049, 0.0064084334298968315, 2915.712158203125
3/10 0.6024811863899231, 0.6014048457145691, 0.6092831492424011, 0.007009853143244982, 915.0398559570312
4/10 0.6314184665679932, 0.6301943063735962, 0.6385058760643005, 0.00734723499044776, 287.9359130859375
5/10 0.6476441621780396, 0.6462849378585815, 0.6548691987991333, 0.007536791265010834, 91.37100982666016
6/10 0.6567531228065491, 0.6552659869194031, 0.664033055305481, 0.007643585558980703, 29.75813865661621
7/10 0.6618777513504028, 0.660266637802124, 0.6691662073135376, 0.007704044692218304, 10.445318222045898
8/10 0.6647716164588928, 0.6630387902259827, 0.672042727470398, 0.007738562300801277, 4.391228199005127
9/10 0.666416585445404, 0.6645633578300476, 0.67365580797195

In [9]:
# 행렬 연산

x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100], 
                               [73,  66,  70]])
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])
x_train.shape, y_train.shape

(torch.Size([5, 3]), torch.Size([5, 1]))

In [10]:
W = torch.zeros((3, 1), requires_grad=True) # x_train (5, 3)과 행렬곱
b = torch.zeros(1, requires_grad=True)
opt = optim.SGD([W, b], lr=1e-5)

epochs = 10
for epoch in range(epochs + 1):
    H = x_train.matmul(W) + b # 행결곱 연산
    C = torch.mean((H - y_train) ** 2)
    
    opt.zero_grad()
    C.backward()
    opt.step()
    
    print(f'{epoch}/{epochs} H : {H.squeeze().detach()}, C : {C.item()}')

0/10 H : tensor([0., 0., 0., 0., 0.]), C : 29661.80078125
1/10 H : tensor([66.7178, 80.1701, 76.1025, 86.0194, 61.1565]), C : 9537.6943359375
2/10 H : tensor([104.5421, 125.6208, 119.2478, 134.7861,  95.8280]), C : 3069.5908203125
3/10 H : tensor([125.9858, 151.3882, 143.7087, 162.4333, 115.4844]), C : 990.6702880859375
4/10 H : tensor([138.1429, 165.9963, 157.5768, 178.1071, 126.6283]), C : 322.48187255859375
5/10 H : tensor([145.0350, 174.2780, 165.4395, 186.9928, 132.9461]), C : 107.7170639038086
6/10 H : tensor([148.9423, 178.9730, 169.8976, 192.0301, 136.5279]), C : 38.687496185302734
7/10 H : tensor([151.1574, 181.6346, 172.4254, 194.8856, 138.5585]), C : 16.499042510986328
8/10 H : tensor([152.4131, 183.1435, 173.8590, 196.5043, 139.7097]), C : 9.365655899047852
9/10 H : tensor([153.1250, 183.9988, 174.6723, 197.4217, 140.3625]), C : 7.071113586425781
10/10 H : tensor([153.5285, 184.4835, 175.1338, 197.9415, 140.7325]), C : 6.331847190856934


# nn.Module로 선형 회귀 구현

In [11]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

model = nn.Linear(in_features=1, out_features=1) # 입/출력 차원
list(model.parameters()) # W, b 출력

[Parameter containing:
 tensor([[0.5153]], requires_grad=True),
 Parameter containing:
 tensor([-0.4414], requires_grad=True)]

In [12]:
opt = torch.optim.SGD(model.parameters(), lr=0.01) # W, b 전달

epochs = 10
for epoch in range(epochs + 1):
    pred = model(x_train) # H(x) 계산
    cost = F.mse_loss(pred, y_train)
    
    opt.zero_grad() # 경사 0 초기화
    cost.backward() # 손실함수 미분
    opt.step() # W, b 업데이트
    
    print(f'{epoch}/{epochs} cost : {cost.item()}')

0/10 cost : 13.103541374206543
1/10 cost : 10.35857105255127
2/10 cost : 8.188817024230957
3/10 cost : 6.473737716674805
4/10 cost : 5.1180548667907715
5/10 cost : 4.046455383300781
6/10 cost : 3.1994102001190186
7/10 cost : 2.5298609733581543
8/10 cost : 2.0006134510040283
9/10 cost : 1.5822678804397583
10/10 cost : 1.251583218574524


In [13]:
new_var = torch.FloatTensor([[4.0]])
pred_y = model(new_var) # forward 연산
pred_y # 최적화 결과 확인

tensor([[6.1553]], grad_fn=<AddmmBackward0>)

In [14]:
list(model.parameters())

[Parameter containing:
 tensor([[1.5381]], requires_grad=True),
 Parameter containing:
 tensor([0.0030], requires_grad=True)]

In [15]:
# 다중 선형 회귀 구현

x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

model = nn.Linear(3, 1) # 다중선형회귀 입/출력
list(model.parameters())

[Parameter containing:
 tensor([[-0.1119,  0.2710, -0.5435]], requires_grad=True),
 Parameter containing:
 tensor([0.3462], requires_grad=True)]

In [16]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5) # 0.00001

epochs = 10
for epoch in range(epochs + 1):
    pred = model(x_train) # H(x) 계산
    cost = F.mse_loss(pred, y_train)
    
    opt.zero_grad() # 경사 0 초기화
    cost.backward() # 손실함수 미분
    opt.step() # W, b 업데이트
    
    print(f'{epoch}/{epochs} cost : {cost.item()}')

0/10 cost : 42134.70703125
1/10 cost : 13211.302734375
2/10 cost : 4145.35107421875
3/10 cost : 1303.652099609375
4/10 cost : 412.92913818359375
5/10 cost : 133.73214721679688
6/10 cost : 46.216514587402344
7/10 cost : 18.782730102539062
8/10 cost : 10.181428909301758
9/10 cost : 7.483162879943848
10/10 cost : 6.635087013244629


In [17]:
new_var =  torch.FloatTensor([[73, 80, 75]])
pred_y = model(new_var)
pred_y

tensor([[154.8908]], grad_fn=<AddmmBackward0>)

In [18]:
list(model.parameters())

[Parameter containing:
 tensor([[0.6839, 1.0633, 0.2607]], requires_grad=True),
 Parameter containing:
 tensor([0.3555], requires_grad=True)]

# 클래스로 파이토치 모델 구현

In [19]:
class LinearRegressionModel(nn.Module): # torch.nn.Module을 상속받는 클래스
    def __init__(self): # 생성자 정의
        super().__init__() # nn.Module의 속성으로 초기화(상속)
        self.linear = nn.Linear(1, 1) # 단순선형회귀
    
    def forward(self, x): # model 객체를 데이터와 호출시 forward 연산
        return self.linear(x)

model = LinearRegressionModel()
model, list(model.parameters())

(LinearRegressionModel(
   (linear): Linear(in_features=1, out_features=1, bias=True)
 ),
 [Parameter containing:
  tensor([[-0.2057]], requires_grad=True),
  Parameter containing:
  tensor([0.5087], requires_grad=True)])

In [20]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

opt = torch.optim.SGD(model.parameters(), lr=0.01)

epochs = 10
for epoch in range(epochs + 1):
    pred = model(x_train)
    cost = F.mse_loss(pred, y_train)
    
    opt.zero_grad()
    cost.backward()
    opt.step()
    
    print(f'{epoch}/{epochs} cost : {cost.item()}')

0/10 cost : 18.47460174560547
1/10 cost : 14.648292541503906
2/10 cost : 11.623584747314453
3/10 cost : 9.232498168945312
4/10 cost : 7.342257022857666
5/10 cost : 5.847909450531006
6/10 cost : 4.6664958000183105
7/10 cost : 3.732438802719116
8/10 cost : 2.9939069747924805
9/10 cost : 2.4099276065826416
10/10 cost : 1.9481143951416016


In [21]:
class MultivariateRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1) # 다중ㅎ선형회구
    
    def forward(self, x):
        return self.linear(x)

model = MultivariateRegressionModel()
model, list(model.parameters())

(MultivariateRegressionModel(
   (linear): Linear(in_features=3, out_features=1, bias=True)
 ),
 [Parameter containing:
  tensor([[ 0.0803, -0.0707,  0.1601]], requires_grad=True),
  Parameter containing:
  tensor([0.0285], requires_grad=True)])

In [22]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

opt = torch.optim.SGD(model.parameters(), lr=1e-5)

epochs = 10
for epoch in range(epochs + 1):
    pred = model(x_train)
    cost = F.mse_loss(pred, y_train)
    
    opt.zero_grad()
    cost.backward()
    opt.step()
    
    print(f'{epoch}/{epochs} cost : {cost.item()}')

0/10 cost : 24821.373046875
1/10 cost : 7780.78271484375
2/10 cost : 2439.46240234375
3/10 cost : 765.2409057617188
4/10 cost : 240.461669921875
5/10 cost : 75.9710693359375
6/10 cost : 24.411727905273438
7/10 cost : 8.250520706176758
8/10 cost : 3.1846110820770264
9/10 cost : 1.5965745449066162
10/10 cost : 1.0986335277557373


# 미니배치와 데이터 로드

* mini batch : 전체 데이터를 작은 단위로 나누어서 학습. 미니배치에 대한 손실 계산하여 경사하강.
* 미니배치의 개수만큼 경사하강을 수행 = 1 에포크 수행
* 미니배치를 적용하면 수렴과정에서 조금 헤매지만, 훈련속도 상승
* iteration = data size / batch size

In [23]:
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

dataset = TensorDataset(x_train, y_train) # 텐서를 입력으로 받음
dataloader = DataLoader(dataset, batch_size=2, shuffle=True) # 배치사이즈는 통상 2의 배수

model = nn.Linear(3, 1)
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

epochs = 10
for epoch in range(epochs + 1):
    for batch_idx, samples in enumerate(dataloader):
        
        x_train, y_train = samples
        
        pred = model(x_train)
        cost = F.mse_loss(pred, y_train)
        
        opt.zero_grad()
        cost.backward()
        opt.step()
        
        print(f'{epoch}/{epochs} batch {batch_idx + 1}/{len(dataloader)}, cost : {cost.item()}')

0/10 batch 1/3, cost : 32868.546875
0/10 batch 2/3, cost : 8253.9765625
0/10 batch 3/3, cost : 3580.59423828125
1/10 batch 1/3, cost : 670.8707885742188
1/10 batch 2/3, cost : 462.1192626953125
1/10 batch 3/3, cost : 113.4438247680664
2/10 batch 1/3, cost : 18.598493576049805
2/10 batch 2/3, cost : 9.061540603637695
2/10 batch 3/3, cost : 4.041672706604004
3/10 batch 1/3, cost : 0.02078815922141075
3/10 batch 2/3, cost : 0.833903431892395
3/10 batch 3/3, cost : 0.6934444904327393
4/10 batch 1/3, cost : 0.16375519335269928
4/10 batch 2/3, cost : 0.7541210651397705
4/10 batch 3/3, cost : 0.2974722385406494
5/10 batch 1/3, cost : 0.3930050730705261
5/10 batch 2/3, cost : 0.13499924540519714
5/10 batch 3/3, cost : 0.50543212890625
6/10 batch 1/3, cost : 0.402871310710907
6/10 batch 2/3, cost : 0.22851325571537018
6/10 batch 3/3, cost : 0.4023658335208893
7/10 batch 1/3, cost : 0.40940040349960327
7/10 batch 2/3, cost : 0.23728951811790466
7/10 batch 3/3, cost : 0.2137453705072403
8/10 batc

In [24]:
new_var = torch.FloatTensor([[73, 80, 75]])
pred_y = model(new_var)
pred_y

tensor([[151.4803]], grad_fn=<AddmmBackward0>)

# 커스텀 데이터셋

In [25]:
class CustomDataset(torch.utils.data.Dataset): # Dataset을 상속하여 커스텀 데이터셋
    def __init__(self):
        """데이터셋 전처리 부분"""
    
    def __len__(self): # 데이터셋 샘플수
        """데이터셋 샘플 수"""
    
    def __getitem__(self, idx):
        """데이터셋에서 특정 샘플을 가져오는 함수"""

In [26]:
# 선형회귀

class CustomDataset(torch.utils.data.Dataset): # Dataset을 상속하여 커스텀 데이터셋
    def __init__(self):
        self.x_data = [[73, 80, 75],
                    [93, 88, 93],
                    [89, 91, 90],
                    [96, 98, 100],
                    [73, 66, 70]]
        self.y_data = [[152], [185], [180], [196], [142]]
    
    def __len__(self): # 데이터셋 샘플수
        return len(self.x_data)
    
    def __getitem__(self, idx):
        x = torch.FloatTensor(self.x_data[idx])
        y = torch.FloatTensor(self.y_data[idx])
        return x, y

dataset = CustomDataset()
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

model = torch.nn.Linear(3, 1)
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

epochs = 10
for epoch in range(epochs + 1):
    for batch_idx, samples in enumerate(dataloader):
        x_train, y_train = samples
        pred = model(x_train)
        cost = F.mse_loss(pred, y_train)
        
        opt.zero_grad()
        cost.backward()
        opt.step()
        
        print(f'{epoch}/{epochs} batch {batch_idx + 1}/{len(dataloader)}, cost : {cost.item()}')

0/10 batch 1/3, cost : 14629.7578125
0/10 batch 2/3, cost : 11342.603515625
0/10 batch 3/3, cost : 2022.75390625
1/10 batch 1/3, cost : 689.2694091796875
1/10 batch 2/3, cost : 134.20736694335938
1/10 batch 3/3, cost : 5.936200141906738
2/10 batch 1/3, cost : 72.03196716308594
2/10 batch 2/3, cost : 1.1696885824203491
2/10 batch 3/3, cost : 0.005811456590890884
3/10 batch 1/3, cost : 30.07878875732422
3/10 batch 2/3, cost : 4.975607872009277
3/10 batch 3/3, cost : 5.224031448364258
4/10 batch 1/3, cost : 1.1434930562973022
4/10 batch 2/3, cost : 17.939682006835938
4/10 batch 3/3, cost : 13.93496036529541
5/10 batch 1/3, cost : 12.485429763793945
5/10 batch 2/3, cost : 6.557172775268555
5/10 batch 3/3, cost : 19.813745498657227
6/10 batch 1/3, cost : 14.490995407104492
6/10 batch 2/3, cost : 10.984434127807617
6/10 batch 3/3, cost : 9.938329696655273
7/10 batch 1/3, cost : 7.2875542640686035
7/10 batch 2/3, cost : 18.251949310302734
7/10 batch 3/3, cost : 9.30838394165039
8/10 batch 1/3

In [27]:
new_var = torch.FloatTensor([[73, 90, 75]])
pred_y = model(new_var)
pred_y

tensor([[162.8903]], grad_fn=<AddmmBackward0>)