In [44]:
import torch
import numpy as np

# Initializing a Tensor

In [5]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device # cuda, cpu 설정

'cpu'

In [4]:
my_tensor = torch.tensor(
    [[1, 2, 3], [4, 5, 6]], 
    dtype=torch.float32,
    device='cpu',
    requires_grad=True # backpropagation
)

my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

In [6]:
my_tensor.dtype, my_tensor.device, my_tensor.shape, my_tensor.requires_grad

(torch.float32, device(type='cpu'), torch.Size([2, 3]), True)

In [13]:
x = torch.empty(size=(3, 3)) # uninitalized data
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [14]:
x = torch.zeros((3, 3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [16]:
x = torch.ones((3, 3))
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [15]:
x = torch.rand((3, 3))
x

tensor([[0.0216, 0.7402, 0.9668],
        [0.6315, 0.3736, 0.6958],
        [0.5727, 0.1008, 0.8029]])

In [19]:
x = torch.eye(5, 5)
x

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [20]:
x = torch.arange(start=0, end=5, step=1)
x

tensor([0, 1, 2, 3, 4])

In [22]:
x = torch.linspace(start=0.1, end=1, steps=10)
x

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [27]:
x = torch.empty(size=(1, 5)).normal_(mean=0, std=1)
x # 무작위 정규화

tensor([[-0.4076,  2.5549, -0.4541, -1.2119, -0.5035]])

In [29]:
x = torch.empty(size=(1, 5)).uniform_(0, 1)
x # uniform distribution

tensor([[0.3950, 0.1866, 0.1350, 0.0970, 0.4575]])

In [30]:
x = torch.diag(torch.ones(3))
x # eye와 유사

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

# Converting tensor types

In [36]:
tensor = torch.arange(4)
tensor, tensor.bool()

(tensor([0, 1, 2, 3]), tensor([False,  True,  True,  True]))

In [41]:
tensor.short(), tensor.long()# int16, int64

(tensor([0, 1, 2, 3], dtype=torch.int16), tensor([0, 1, 2, 3]))

In [43]:
tensor.half(), tensor.float(), tensor.double() # float16, float32, float64

(tensor([0., 1., 2., 3.], dtype=torch.float16),
 tensor([0., 1., 2., 3.]),
 tensor([0., 1., 2., 3.], dtype=torch.float64))

In [45]:
np_array = np.zeros((5, 5))
np_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [46]:
tensor = torch.from_numpy(np_array)
tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)

In [47]:
tensor.numpy()

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Tensor math

In [51]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])
z1 = torch.empty(3)

x, y, z1

(tensor([1, 2, 3]),
 tensor([9, 8, 7]),
 tensor([-1.2610e-29,  4.5914e-41,  0.0000e+00]))

In [52]:
torch.add(x, y, out=z1)
z1

tensor([10., 10., 10.])

In [55]:
z2 = torch.add(x, y)
z2

tensor([10, 10, 10])

In [56]:
z = x + y
z

tensor([10, 10, 10])

In [58]:
z = x - y
z

tensor([-8, -6, -4])

In [59]:
z = torch.true_divide(x, y)
z

tensor([0.1111, 0.2500, 0.4286])

In [60]:
t = torch.zeros(3)
t.add_(x) # inplace
t

tensor([1., 2., 3.])

In [61]:
s = torch.zeros(3)
s += x
s

tensor([1., 2., 3.])

In [62]:
z = x.pow(2)
z

tensor([1, 4, 9])

In [63]:
z = x ** 2
z

tensor([1, 4, 9])

In [64]:
z = x > 0
z

tensor([True, True, True])

In [66]:
x1 = torch.rand((2, 5))
x2 = torch.rand((5, 3))
x3 = torch.mm(x1, x2) # 2x3

x1, x2, x3

(tensor([[0.1806, 0.9584, 0.9985, 0.2573, 0.2838],
         [0.3456, 0.9936, 0.1004, 0.7164, 0.3198]]),
 tensor([[0.6307, 0.6326, 0.3861],
         [0.4852, 0.0037, 0.8272],
         [0.8854, 0.7495, 0.7516],
         [0.8264, 0.3007, 0.1081],
         [0.5148, 0.4504, 0.5064]]),
 tensor([[1.8217, 1.0713, 1.7844],
         [1.5457, 0.6570, 1.2702]]))

In [67]:
x3 = x1.mm(x2)
x3

tensor([[1.8217, 1.0713, 1.7844],
        [1.5457, 0.6570, 1.2702]])