In [1]:
import torch
import numpy as np

# Initializing a Tensor

In [2]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device # cuda, cpu 설정

'cpu'

In [3]:
my_tensor = torch.tensor(
    [[1, 2, 3], [4, 5, 6]], 
    dtype=torch.float32,
    device='cpu',
    requires_grad=True # backpropagation
)

my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

In [4]:
my_tensor.dtype, my_tensor.device, my_tensor.shape, my_tensor.requires_grad

(torch.float32, device(type='cpu'), torch.Size([2, 3]), True)

In [5]:
torch.empty(size=(3, 3)) # uninitalized data

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.zeros((3, 3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.ones((3, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [8]:
torch.rand((3, 3))

tensor([[0.1743, 0.1913, 0.6238],
        [0.0742, 0.7109, 0.6614],
        [0.8056, 0.5717, 0.4232]])

In [9]:
torch.eye(5, 5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [10]:
torch.arange(start=0, end=5, step=1)

tensor([0, 1, 2, 3, 4])

In [11]:
torch.linspace(start=0.1, end=1, steps=10)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [12]:
torch.empty(size=(1, 5)).normal_(mean=0, std=1) # 무작위 정규화

tensor([[ 0.6033, -1.1576, -0.0068, -0.0263, -0.3571]])

In [13]:
torch.empty(size=(1, 5)).uniform_(0, 1) # uniform distribution

tensor([[0.6956, 0.2468, 0.9042, 0.4965, 0.2303]])

In [14]:
torch.diag(torch.ones(3)) # eye와 유사

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

# Converting tensor types

In [15]:
tensor = torch.arange(4)
tensor, tensor.bool()

(tensor([0, 1, 2, 3]), tensor([False,  True,  True,  True]))

In [16]:
tensor.short(), tensor.long()# int16, int64

(tensor([0, 1, 2, 3], dtype=torch.int16), tensor([0, 1, 2, 3]))

In [17]:
tensor.half(), tensor.float(), tensor.double() # float16, float32, float64

(tensor([0., 1., 2., 3.], dtype=torch.float16),
 tensor([0., 1., 2., 3.]),
 tensor([0., 1., 2., 3.], dtype=torch.float64))

In [18]:
np_array = np.zeros((5, 5))
np_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
tensor = torch.from_numpy(np_array)
tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)

In [20]:
tensor.numpy()

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Tensor math

In [21]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])
z1 = torch.empty(3)

x, y, z1

(tensor([1, 2, 3]),
 tensor([9, 8, 7]),
 tensor([3.3382e-09, 6.5548e-10, 7.9871e+20]))

In [22]:
torch.add(x, y, out=z1)

tensor([10., 10., 10.])

In [23]:
torch.add(x, y)

tensor([10, 10, 10])

In [24]:
x + y, x - y

(tensor([10, 10, 10]), tensor([-8, -6, -4]))

In [25]:
torch.true_divide(x, y)

tensor([0.1111, 0.2500, 0.4286])

In [26]:
t = torch.zeros(3)
t.add_(x) # inplace

tensor([1., 2., 3.])

In [27]:
s = torch.zeros(3)
s += x
s

tensor([1., 2., 3.])

In [28]:
x.pow(2), x ** 2

(tensor([1, 4, 9]), tensor([1, 4, 9]))

In [29]:
z = x > 0
z

tensor([True, True, True])

In [30]:
x1 = torch.rand((2, 5))
x2 = torch.rand((5, 3))
x3 = torch.mm(x1, x2) # 2x3

torch.mm(x1, x2), x1.mm(x2)

(tensor([[0.8101, 0.7566, 1.4897],
         [1.2323, 1.0847, 1.7547]]),
 tensor([[0.8101, 0.7566, 1.4897],
         [1.2323, 1.0847, 1.7547]]))

In [31]:
mat_exp = torch.rand(5, 5)
mat_exp.matrix_power(3)

tensor([[3.5410, 3.3953, 2.6122, 2.4495, 4.3629],
        [2.2059, 2.4428, 1.8312, 1.6105, 2.7435],
        [2.6982, 2.5345, 2.1561, 2.0151, 3.5362],
        [3.3751, 3.3302, 2.3130, 2.4473, 3.9787],
        [2.2860, 2.4682, 1.8035, 1.7944, 3.0039]])

In [32]:
x * y # elementwise mult

tensor([ 9, 16, 21])

In [33]:
torch.dot(x, y)

tensor(46)

In [34]:
batch = 32
n, m, p = 10, 20, 30

tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))

out = torch.bmm(tensor1, tensor2) # (batch, n, p)
out.shape

torch.Size([32, 10, 30])

In [35]:
x1 = torch.rand((5, 5))
x2 = torch.rand((1, 5))
z = x1 - x2

x1, x2, z # expand calc

(tensor([[0.2680, 0.4210, 0.0185, 0.9006, 0.8948],
         [0.3524, 0.1343, 0.8091, 0.5857, 0.8438],
         [0.9853, 0.3632, 0.3174, 0.8196, 0.5174],
         [0.8355, 0.1515, 0.1727, 0.4810, 0.3228],
         [0.3998, 0.5920, 0.5756, 0.2879, 0.2584]]),
 tensor([[0.4940, 0.0806, 0.7487, 0.8377, 0.7135]]),
 tensor([[-0.2260,  0.3405, -0.7301,  0.0629,  0.1813],
         [-0.1416,  0.0538,  0.0604, -0.2520,  0.1303],
         [ 0.4913,  0.2826, -0.4312, -0.0181, -0.1961],
         [ 0.3414,  0.0709, -0.5759, -0.3567, -0.3907],
         [-0.0942,  0.5114, -0.1730, -0.5498, -0.4551]]))

In [36]:
x, torch.sum(x, dim=0)

(tensor([1, 2, 3]), tensor(6))

In [37]:
values, indices = torch.max(x, dim=0) # min()
x, values, indices

(tensor([1, 2, 3]), tensor(3), tensor(2))

In [38]:
torch.abs(x)

tensor([1, 2, 3])

In [39]:
torch.argmax(x, dim=0)

tensor(2)

In [40]:
torch.mean(x.float(), dim=0)

tensor(2.)

In [41]:
torch.eq(x, y) # equal

tensor([False, False, False])

In [42]:
torch.sort(y, dim=0, descending=False)

torch.return_types.sort(
values=tensor([7, 8, 9]),
indices=tensor([2, 1, 0]))

In [43]:
torch.clamp(x, min=10) # 기준으로 조정

tensor([10, 10, 10])

In [44]:
x = torch.tensor([1, 0, 1], dtype=torch.bool)
torch.any(x), torch.all(x)

(tensor(True), tensor(False))

# Tensor Indexing

In [45]:
batch_size = 10
features = 25
x = torch.rand((batch_size, features))
x[0], x[0].shape, x[:, 0].shape, x[2, 0:10]

(tensor([0.8949, 0.3887, 0.2508, 0.9686, 0.2389, 0.2567, 0.9754, 0.6493, 0.7892,
         0.2028, 0.3143, 0.8226, 0.7555, 0.1461, 0.8430, 0.2014, 0.6159, 0.1865,
         0.1137, 0.5962, 0.3235, 0.8813, 0.2434, 0.1997, 0.5350]),
 torch.Size([25]),
 torch.Size([10]),
 tensor([0.0739, 0.7425, 0.5778, 0.0068, 0.7443, 0.5374, 0.2747, 0.7115, 0.0597,
         0.0370]))

In [46]:
x = torch.arange(10)
indices = [2, 5, 8]
x[indices]

tensor([2, 5, 8])

In [47]:
x = torch.rand((3, 5))
rows = torch.tensor([1, 0])
cols = torch.tensor([4, 0])
x[rows, cols]

tensor([0.3654, 0.3645])

In [48]:
x = torch.arange(10)
x[(x < 2) | (x > 8)]

tensor([0, 1, 9])

In [49]:
x[x.remainder(2) == 0] # 나머지

tensor([0, 2, 4, 6, 8])

In [50]:
torch.where(x > 5, x, x * 2)

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])

In [51]:
torch.tensor([0, 0, 1, 2, 3]).unique()

tensor([0, 1, 2, 3])

In [52]:
x.ndimension()

1

In [53]:
x.numel() # 총 개수

10

# Tensor Reshaping Dimensions

In [54]:
x = torch.arange(9)
a = x.view(3, 3)
b = x.reshape(3, 3)

a, b

(tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]),
 tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]))

In [55]:
x1 = torch.rand((2, 5))
x2 = torch.rand((2, 5))

torch.cat((x1, x2), dim=0).shape

torch.Size([4, 5])

In [56]:
torch.cat((x1, x2), dim=1).shape

torch.Size([2, 10])

In [57]:
x1.view(-1).shape

torch.Size([10])

In [58]:
batch = 64
x = torch.rand((batch, 2, 5))
x.shape

torch.Size([64, 2, 5])

In [59]:
x.view(batch, -1).shape

torch.Size([64, 10])

In [60]:
x.permute(0, 2, 1).shape

torch.Size([64, 5, 2])

In [61]:
x = torch.arange(10)
x.shape

torch.Size([10])

In [62]:
x.unsqueeze(0).shape

torch.Size([1, 10])

In [63]:
x.unsqueeze(1).shape

torch.Size([10, 1])